# This workflow runs PHPUnit tests for the openconnector app (Simplified)
#
# SPDX-FileCopyrightText: 2024 Nextcloud GmbH and Nextcloud contributors
# SPDX-License-Identifier: MIT

name: PHPUnit Tests (Simplified)

on:
  pull_request:
    paths:
      - '**'
  push:
    branches: [main, master, development]
    paths:
      - '**'

permissions:
  contents: read

concurrency:
  group: phpunit-openconnector-simple-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  phpunit-openconnector-simple:
    runs-on: ubuntu-latest

    name: OpenConnector (Simplified - PHP 8.3)

    steps:
      - name: Checkout openconnector
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          submodules: true

      - name: Set up php 8.3
        uses: shivammathur/setup-php@2e947f1f6932d141d076ca441d0e1e881775e95b #v2.31.0
        with:
          php-version: '8.3'
          extensions: bz2, ctype, curl, dom, fileinfo, gd, iconv, intl, json, libxml, mbstring, openssl, pcntl, posix, redis, session, simplexml, xmlreader, xmlwriter, zip, zlib, sqlite, pdo_sqlite
          coverage: none
          ini-file: development

      - name: Install dependencies
        run: composer install

      - name: Install PHPUnit globally
        run: |
          wget -O phpunit https://phar.phpunit.de/phpunit-9.6.phar
          chmod +x phpunit
          sudo mv phpunit /usr/local/bin/

      - name: Create bootstrap file
        run: |
          cat > tests/bootstrap.php << 'EOF'
          <?php
          // Simple bootstrap for unit tests
          require_once __DIR__ . '/../vendor/autoload.php';
          
          // Create simple mock classes for Nextcloud interfaces
          if (!interface_exists('OCP\IRequest')) {
              interface OCP\IRequest {}
          }
          if (!interface_exists('OCP\IUserManager')) {
              interface OCP\IUserManager {}
          }
          if (!interface_exists('OCP\IUserSession')) {
              interface OCP\IUserSession {}
          }
          if (!interface_exists('OCP\ICacheFactory')) {
              interface OCP\ICacheFactory {}
          }
          if (!interface_exists('OCP\IUser')) {
              interface OCP\IUser {}
          }
          if (!interface_exists('Psr\Log\LoggerInterface')) {
              interface Psr\Log\LoggerInterface {}
          }
          EOF

      - name: Run PHPUnit tests
        run: phpunit --bootstrap tests/bootstrap.php tests/Unit/

      - name: Run PHPUnit tests (alternative command)
        if: failure()
        run: |
          echo "Trying alternative approach..."
          find tests/ -name "*.php" -exec php -l {} \;
          echo "All PHP files are syntactically valid"
