# This workflow runs PHPUnit tests for the openconnector app (Simple)
#
# SPDX-FileCopyrightText: 2024 Nextcloud GmbH and Nextcloud contributors
# SPDX-License-Identifier: MIT

name: PHPUnit Tests (Simple)

on:
  pull_request:
    paths:
      - '**'
  push:
    branches: [main, master, development]
    paths:
      - '**'

permissions:
  contents: read

concurrency:
  group: phpunit-openconnector-simple-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  phpunit-openconnector:
    runs-on: ubuntu-latest

    name: OpenConnector (Simple - PHP 8.3)

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup PHP Composer Environment
        uses: php-actions/composer@v6
        with:
          php_version: "8.3"
          php_extensions: redis exif intl zip pcntl gd gmp
          version: 2.x
          command: install

      - name: Run tests
        run: php vendor/bin/phpunit --configuration phpunit.xml --coverage-text
