# This workflow runs PHPUnit tests for the openconnector app
#
# SPDX-FileCopyrightText: 2024 Nextcloud GmbH and Nextcloud contributors
# SPDX-License-Identifier: MIT

name: PHPUnit Tests

on:
  pull_request:
    paths:
      - '**'
  push:
    branches: [main, master, development]
    paths:
      - '**'

permissions:
  contents: read

concurrency:
  group: phpunit-openconnector-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  phpunit-openconnector:
    runs-on: ubuntu-latest

    name: OpenConnector (PHP 8.3)

    steps:
      - name: Checkout openconnector
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          submodules: true

      - name: Set up php 8.3
        uses: shivammathur/setup-php@2e947f1f6932d141d076ca441d0e1e881775e95b #v2.31.0
        with:
          php-version: '8.3'
          extensions: bz2, ctype, curl, dom, fileinfo, gd, iconv, intl, json, libxml, mbstring, openssl, pcntl, posix, redis, session, simplexml, xmlreader, xmlwriter, zip, zlib, sqlite, pdo_sqlite
          coverage: none
          ini-file: development

      - name: Install dependencies
        run: composer install

      - name: Run PHPUnit tests
        run: vendor/bin/phpunit tests/
