# This workflow runs PHPUnit tests for the openconnector app
#
# SPDX-FileCopyrightText: 2024 Nextcloud GmbH and Nextcloud contributors
# SPDX-License-Identifier: MIT

name: PHPUnit Tests

on:
  pull_request:
    paths:
      - 'apps-extra/openconnector/**'
      - '.github/workflows/phpunit.yml'
  push:
    branches: [main, master, development]
    paths:
      - 'apps-extra/openconnector/**'
      - '.github/workflows/phpunit.yml'

permissions:
  contents: read

concurrency:
  group: phpunit-openconnector-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  phpunit-openconnector:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-versions: ['8.1', '8.2', '8.3']

    name: OpenConnector (PHP ${{ matrix.php-versions }})

    services:
      cache:
        image: ghcr.io/nextcloud/continuous-integration-redis:latest
        ports:
          - 6379:6379/tcp
        options: --health-cmd="redis-cli ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout server
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          submodules: true

      - name: Set up php ${{ matrix.php-versions }}
        uses: shivammathur/setup-php@2e947f1f6932d141d076ca441d0e1e881775e95b #v2.31.0
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: bz2, ctype, curl, dom, fileinfo, gd, iconv, intl, json, libxml, mbstring, openssl, pcntl, posix, redis, session, simplexml, xmlreader, xmlwriter, zip, zlib, sqlite, pdo_sqlite
          coverage: none
          ini-file: development
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up dependencies
        run: composer i

      - name: Set up Nextcloud
        run: |
          mkdir data
          cp tests/redis.config.php config/
          cp tests/preseed-config.php config/config.php
          ./occ maintenance:install --verbose --database=sqlite --database-name=nextcloud --database-user=root --database-pass=rootpassword --admin-user admin --admin-pass admin
          php -f tests/enable_all.php | grep -i -C9999 error && echo "Error during app setup" && exit 1 || exit 0

      - name: Enable OpenConnector app
        run: ./occ app:enable openconnector

      - name: Nextcloud debug information
        run: ./occ app:list && echo "======= System config =======" && ./occ config:list system

      - name: Run OpenConnector PHPUnit tests
        run: phpunit --bootstrap tests/bootstrap.php apps-extra/openconnector/tests

      - name: Print logs
        if: always()
        run: |
          cat data/nextcloud.log
