# This workflow runs PHPUnit tests for the openconnector app
#
# SPDX-FileCopyrightText: 2024 Nextcloud GmbH and Nextcloud contributors
# SPDX-License-Identifier: MIT

name: PHPUnit Tests

on:
  pull_request:
    paths:
      - '**'
  push:
    branches: [main, master, development]
    paths:
      - '**'

permissions:
  contents: read

concurrency:
  group: phpunit-openconnector-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  phpunit-openconnector:
    runs-on: ubuntu-latest

    name: OpenConnector (PHP 8.3)

    services:
      cache:
        image: ghcr.io/nextcloud/continuous-integration-redis:latest
        ports:
          - 6379:6379/tcp
        options: --health-cmd="redis-cli ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout openconnector
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          submodules: true

      - name: Checkout Nextcloud server
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          repository: nextcloud/server
          path: server
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up php 8.3
        uses: shivammathur/setup-php@2e947f1f6932d141d076ca441d0e1e881775e95b #v2.31.0
        with:
          php-version: '8.3'
          extensions: bz2, ctype, curl, dom, fileinfo, gd, iconv, intl, json, libxml, mbstring, openssl, pcntl, posix, redis, session, simplexml, xmlreader, xmlwriter, zip, zlib, sqlite, pdo_sqlite
          coverage: none
          ini-file: development

      - name: Set up dependencies
        run: |
          cd server
          git submodule update --init --recursive
          composer i

      - name: Copy openconnector app to server
        run: |
          mkdir -p server/apps-extra/openconnector
          # Copy all files and directories except server directory
          for item in *; do
            if [ "$item" != "server" ]; then
              cp -r "$item" server/apps-extra/openconnector/
            fi
          done

      - name: Set up Nextcloud
        run: |
          cd server
          mkdir data
          cp tests/redis.config.php config/
          cp tests/preseed-config.php config/config.php
          ./occ maintenance:install --verbose --database=sqlite --database-name=nextcloud --database-user=root --database-pass=rootpassword --admin-user admin --admin-pass admin
          php -f tests/enable_all.php | grep -i -C9999 error && echo "Error during app setup" && exit 1 || exit 0

      - name: Enable OpenConnector app
        run: cd server && ./occ app:enable openconnector

      - name: Install PHPUnit in server
        run: |
          cd server
          wget -O phpunit https://phar.phpunit.de/phpunit-9.6.phar
          chmod +x phpunit

      - name: Run PHPUnit tests
        run: cd server && ./phpunit --bootstrap tests/bootstrap.php apps-extra/openconnector/tests
        continue-on-error: false
