name: Unit Tests

on:
  pull_request:
    branches:
      - development
      - main
      - master
  push:
    branches:
      - development
      - main
      - master

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        php-version: ['8.1', '8.2', '8.3']
    
    name: PHP ${{ matrix.php-version }} Unit Tests
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite, dom, filter, gd, iconv, json, mbstring, pdo, zip, curl, mysql
          coverage: xdebug
          tools: composer:v2
          
      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
        
      - name: Cache composer dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-
            
      - name: Update composer lock file
        run: composer update --lock --no-interaction
        
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-interaction --optimize-autoloader
        
      - name: Verify PHPUnit is available
        run: |
          if [ ! -f "./vendor/bin/phpunit" ]; then
            echo "PHPUnit not found, installing..."
            composer require --dev phpunit/phpunit:^9.6 --no-interaction
          fi
          ./vendor/bin/phpunit --version
        
      - name: Create test database
        run: |
          mkdir -p tests/data
          touch tests/data/test.db
          
      - name: Run PHP linting
        run: composer lint
        continue-on-error: true
        
      - name: Verify PHPUnit installation
        run: |
          # Check if PHPUnit is available
          if [ ! -f "./vendor/bin/phpunit" ]; then
            echo "PHPUnit not found, installing..."
            composer require --dev phpunit/phpunit:^9.6
          fi
          
          # Verify PHPUnit works
          ./vendor/bin/phpunit --version
        
      - name: Run unit tests
        run: composer test:unit
        
      - name: Upload coverage reports
        if: matrix.php-version == '8.2'
        uses: codecov/codecov-action@v4
        with:
          file: ./coverage.xml
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: false
